name: Sauce Demo UI Automation CI

on:
  push:
    branches: [ "main", "master" ]


permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Selenium Tests via Maven
        run: mvn clean test -Dheadless=true

      # سحب الـ History بأمان بدون ما يضرب لو الـ branch مش موجود لسه
      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages-dir
        continue-on-error: true

      # استخدام نسخة مستقرة ومجربة وبتشتغل بدون Docker ومشاكله
      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      # الـ Deploy المظبوط للفولدر النظيف
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history